config/routes.rb
BurgerMarks::Application.routes.draw do
  get "content/index"

  get "content/about"

  devise_for :users, :path_names => { :sign_in => 'login', :sign_out => 'logout' }

  resources :marks

  resources :burgers

  root :to => "content#index"

end

app/models/brand.rb
class Brand < ActiveRecord::Base
  has_many :burger
end

app/models/burger.rb
class Burger < ActiveRecord::Base
  has_many :marks
  belongs_to :brand

  has_attached_file :photo, :styles => { :small => "150x150>" },
                    :url  => "/assets/burgers/:id/:style/:basename.:extension",
                    :path => ":rails_root/public/assets/burgers/:id/:style/:basename.:extension"

  validates_attachment_presence :photo
  validates_attachment_size :photo, :less_than => 5.megabytes
  validates_attachment_content_type :photo, :content_type => ['image/jpeg', 'image/png']

end

app/models/mark.rb
class Mark < ActiveRecord::Base
  belongs_to :user
  belongs_to :burger
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :marks

  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable

#  has_attached_file :avatar, :styles => { :small => "150x150>" },
#                    :url  => "/assets/users/:id/:style/:basename.:extension",
#                    :path => ":rails_root/public/assets/users/:id/:style/:basename.:extension"
#
#  validates_attachment_presence :avatar
#  validates_attachment_size :avatar, :less_than => 5.megabytes
#  validates_attachment_content_type :avatar, :content_type => ['image/jpeg', 'image/png']


  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :first_name, :last_name, :nickname
#  attr_accessible :avatar, :avatar_file_name, :avatar_content_type, :avatar_size

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/burgers_controller.rb
class BurgersController < ApplicationController
  before_filter :authenticate_user!, :only => [:new,:create,:update,:edit]

  # GET /burgers
  # GET /burgers.xml
  def index
    @burgers = Burger.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @burgers }
    end
  end

  # GET /burgers/1
  # GET /burgers/1.xml
  def show
    @burger = Burger.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @burger }
    end
  end

  # GET /burgers/new
  # GET /burgers/new.xml
  def new

    @burger = Burger.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @burger }
    end
  end

  # GET /burgers/1/edit
  def edit
    @burger = Burger.find(params[:id])
  end

  # POST /burgers
  # POST /burgers.xml
  def create
    @burger = Burger.new(params[:burger])

    respond_to do |format|
      if @burger.save
        format.html { redirect_to(@burger, :notice => 'Burger was successfully created.') }
        format.xml  { render :xml => @burger, :status => :created, :location => @burger }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @burger.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /burgers/1
  # PUT /burgers/1.xml
  def update
    @burger = Burger.find(params[:id])

    respond_to do |format|
      if @burger.update_attributes(params[:burger])
        format.html { redirect_to(@burger, :notice => 'Burger was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @burger.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /burgers/1
  # DELETE /burgers/1.xml
  def destroy
    @burger = Burger.find(params[:id])
    @burger.destroy

    respond_to do |format|
      format.html { redirect_to(burgers_url) }
      format.xml  { head :ok }
    end
  end
end

app/controllers/content_controller.rb
class ContentController < ApplicationController
  def index
  end

  def about
  end

end

app/controllers/marks_controller.rb
class MarksController < ApplicationController
  # GET /marks
  # GET /marks.xml
  def index
    @marks = Mark.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @marks }
    end
  end

  # GET /marks/1
  # GET /marks/1.xml
  def show
    @mark = Mark.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @mark }
    end
  end

  # GET /marks/new
  # GET /marks/new.xml
  def new
    @mark = Mark.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @mark }
    end
  end

  # GET /marks/1/edit
  def edit
    @mark = Mark.find(params[:id])
  end

  # POST /marks
  # POST /marks.xml
  def create
    @mark = Mark.new(params[:mark])

    respond_to do |format|
      if @mark.save
        format.html { redirect_to(@mark, :notice => 'Mark was successfully created.') }
        format.xml  { render :xml => @mark, :status => :created, :location => @mark }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @mark.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /marks/1
  # PUT /marks/1.xml
  def update
    @mark = Mark.find(params[:id])

    respond_to do |format|
      if @mark.update_attributes(params[:mark])
        format.html { redirect_to(@mark, :notice => 'Mark was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @mark.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /marks/1
  # DELETE /marks/1.xml
  def destroy
    @mark = Mark.find(params[:id])
    @mark.destroy

    respond_to do |format|
      format.html { redirect_to(marks_url) }
      format.xml  { head :ok }
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # GET /users
  # GET /users.xml
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @users }
    end
  end

  # GET /users/1
  # GET /users/1.xml
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @user }
    end
  end

  # GET /users/new
  # GET /users/new.xml
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.xml
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to(@user, :notice => 'User was successfully created.') }
        format.xml  { render :xml => @user, :status => :created, :location => @user }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @user.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.xml
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to(@user, :notice => 'User was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @user.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.xml
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to(users_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/burgers_helper.rb
module BurgersHelper
end

app/helpers/content_helper.rb
module ContentHelper
end

app/helpers/marks_helper.rb
module MarksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/burgers/_form.html.erb
<%= semantic_form_for @burger, :html => { :multipart => true } do |f| %>
  <% if @burger.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@burger.errors.count, "error") %> prohibited this burger from being saved:</h2>

      <ul>
      <% @burger.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <%= f.inputs do %>
    <%= f.input :name %>
    <%= f.input :description %>
    <%= f.input :brand, :collection => Brand.all %>
    <%= f.input :photo, :as => :file %>
    <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/burgers/edit.html.erb
<h1>Editing burger</h1>

<%= render 'form' %>

<%= link_to 'Show', @burger %> |
<%= link_to 'Back', burgers_path %>

app/views/burgers/index.html.erb
<h1>Listing burgers</h1>

<table class="burger_table">
  <tr>
    <th>Position</th>
    <th>Picture</th>
    <th>Name</th>
    <th>Description</th>
    <th>Brand</th>
    <th></th>
  </tr>

<% @burgers.each do |burger| %>
  <tr>
    <td></td>
    <td><%= image_tag burger.photo.url(:small) %></td>
    <td><%= burger.name %></td>
    <td class="burger_description"><%= burger.description %></td>
    <td><%= burger.brand.name %></td>
    <td><%= link_to 'Show', burger %><br />
    <%= link_to 'Edit', edit_burger_path(burger) %><br />
    <%= link_to 'Destroy', burger, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Burger', new_burger_path %>

app/views/burgers/new.html.erb
<h1>New burger</h1>

<%= render 'form' %>

<%= link_to 'Back', burgers_path %>

app/views/burgers/show.html.erb
<p id="notice"><%= notice %></p>
<%= image_tag @burger.photo.url(:small) %>



<p>
  <b>Name:</b>
  <%= @burger.name %>
</p>

<p>
  <b>Description:</b>
  <%= @burger.description %>
</p>

<p>
  <b>Brand:</b>
  <%= @burger.brand %>
</p>


<%= link_to 'Edit', edit_burger_path(@burger) %> |
<%= link_to 'Back', burgers_path %>

app/views/content/about.html.erb
<h1>Content#about</h1>
<p>Find me in app/views/content/about.html.erb</p>

app/views/content/index.html.erb
<h1>Bienvenue sur BurgerMarks</h1>

<ul>
    <li><%= link_to "Top Burger", burgers_path %></li>
  <% if user_signed_in? %>
    <li><%= link_to "Ajouter un Burger", new_burger_path %></li>
  <% else %>
    <li><%= link_to t("Sign up"), new_user_registration_path %></li>
    <li><%= link_to t("Sign in"), new_user_session_path %></li>
  <% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BurgerMarks</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>
<% flash.each do |key, value| %>
  <p class="flash <%= key %>"><%= value %></p>
<% end %>

<div id="big_wrapper">

  <img src="/images/logo.png" style="margin:auto; height: 120px;" onclick="location.href='<%= url_for root_url %>'" /><p style="float:right; color: white;">Beta v0.1 Moche</p>


  <div id="wrapper">

    <div id="header">
      <img src="/images/burger.png" />
      <img src="/images/burger.png" />
      <img src="/images/burger.png" />
      <img src="/images/burger.png" />
      <img src="/images/burger.png" />
      <img src="/images/burger.png" />
      <img src="/images/burger.png" />
      <img src="/images/burger.png" />
    </div>

    <div id="user_nav">
      <% if user_signed_in? %>
        Connecté sur <%= current_user.email %>. Ce n'est pas vous ?
        <%= link_to "Se déconnecter", destroy_user_session_path %>
      <% else %>
        <%= link_to "S'inscrire", new_user_registration_path %> ou <%= link_to "se connecter", new_user_session_path %>
      <% end %>
    </div>
    <%= yield %>
  </div>
</div>
</body>
</html>

app/views/marks/_form.html.erb
<%= form_for(@mark) do |f| %>
  <% if @mark.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@mark.errors.count, "error") %> prohibited this mark from being saved:</h2>

      <ul>
      <% @mark.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :mark %><br />
    <%= f.text_field :mark %>
  </div>
  <div class="field">
    <%= f.label :comment %><br />
    <%= f.text_area :comment %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/marks/edit.html.erb
<h1>Editing mark</h1>

<%= render 'form' %>

<%= link_to 'Show', @mark %> |
<%= link_to 'Back', marks_path %>

app/views/marks/index.html.erb
<h1>Listing marks</h1>

<table>
  <tr>
    <th>Mark</th>
    <th>Comment</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @marks.each do |mark| %>
  <tr>
    <td><%= mark.mark %></td>
    <td><%= mark.comment %></td>
    <td><%= link_to 'Show', mark %></td>
    <td><%= link_to 'Edit', edit_mark_path(mark) %></td>
    <td><%= link_to 'Destroy', mark, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Mark', new_mark_path %>

app/views/marks/new.html.erb
<h1>New mark</h1>

<%= render 'form' %>

<%= link_to 'Back', marks_path %>

app/views/marks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Mark:</b>
  <%= @mark.mark %>
</p>

<p>
  <b>Comment:</b>
  <%= @mark.comment %>
</p>


<%= link_to 'Edit', edit_mark_path(@mark) %> |
<%= link_to 'Back', marks_path %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :first_name %><br />
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br />
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label :nickname %><br />
    <%= f.text_field :nickname %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <tr>
    <th>First name</th>
    <th>Last name</th>
    <th>Nickname</th>
    <th>Email</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.first_name %></td>
    <td><%= user.last_name %></td>
    <td><%= user.nickname %></td>
    <td><%= user.email %></td>
    <td><%= link_to 'Show', user %></td>
    <td><%= link_to 'Edit', edit_user_path(user) %></td>
    <td><%= link_to 'Destroy', user, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>First name:</b>
  <%= @user.first_name %>
</p>

<p>
  <b>Last name:</b>
  <%= @user.last_name %>
</p>

<p>
  <b>Nickname:</b>
  <%= @user.nickname %>
</p>

<p>
  <b>Email:</b>
  <%= @user.email %>
</p>


<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>